
CONSTANTS_ONE_G = 9.80665;						% m/s^2
CONSTANTS_STD_PRESSURE_PA = 101325.0;					% pascals (Pa)
CONSTANTS_STD_PRESSURE_KPA = CONSTANTS_STD_PRESSURE_PA / 1000.0;	% kilopascals (kPa)
CONSTANTS_STD_PRESSURE_MBAR = CONSTANTS_STD_PRESSURE_PA / 100.0;	% Millibar (mbar) (1 mbar = 100 Pa)
CONSTANTS_AIR_DENSITY_SEA_LEVEL_15C = 1.225;				% kg/m^3
CONSTANTS_AIR_GAS_CONST = 287.1;					% J/(kg * K)
CONSTANTS_ABSOLUTE_NULL_CELSIUS = -273.15;				% °C
CONSTANTS_RADIUS_OF_EARTH = 6371000;					% meters (m)
CONSTANTS_RADIUS_OF_EARTH_F = CONSTANTS_RADIUS_OF_EARTH;		% meters (m)
CONSTANTS_EARTH_SPIN_RATE = 7.2921150e-5;


MISSION_ORIGIN_MAVLINK = uint8(0);
MISSION_ORIGIN_ONBOARD = uint8(1);