function commander_consts()

PARAM_DEFINE_START();

PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_MANUAL', uint8(1));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_ALTCTL', uint8(2));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_POSCTL', uint8(3));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_AUTO', uint8(4));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_ACRO', uint8(5));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_OFFBOARD', uint8(6));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_STABILIZED', uint8(7));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_RATTITUDE_LEGACY', uint8(8));
PARAM_DEFINE_CONST('CUSTOM_MAIN_MODE_SIMPLE', uint8(9));

PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_READY', uint8(1));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_TAKEOFF', uint8(2));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_LOITER', uint8(3));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_MISSION', uint8(4));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_RTL', uint8(5));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_LAND', uint8(6));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_RESERVED_DO_NOT_USE', uint8(7)); % was CUSTOM_SUB_MODE_AUTO_RTGS; deleted 2020-03-05
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET', uint8(8));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_AUTO_PRECLAND', uint8(9));

PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_POSCTL_POSCTL', uint8(0));
PARAM_DEFINE_CONST('CUSTOM_SUB_MODE_POSCTL_ORBIT', uint8(1));

PARAM_DEFINE_CONST('CBRK_BUZZER_KEY', uint32(782097));
PARAM_DEFINE_CONST('CBRK_SUPPLY_CHK_KEY', uint32(894281));
PARAM_DEFINE_CONST('CBRK_RATE_CTRL_KEY', uint32(140253));
PARAM_DEFINE_CONST('CBRK_IO_SAFETY_KEY', uint32(22027));
PARAM_DEFINE_CONST('CBRK_AIRSPD_CHK_KEY', uint32(162128));
PARAM_DEFINE_CONST('CBRK_FLIGHTTERM_KEY', uint32(121212));
PARAM_DEFINE_CONST('CBRK_ENGINEFAIL_KEY', uint32(284953));
PARAM_DEFINE_CONST('CBRK_USB_CHK_KEY', uint32(197848));
PARAM_DEFINE_CONST('CBRK_VELPOSERR_KEY', uint32(201607));
PARAM_DEFINE_CONST('CBRK_VTOLARMING_KEY', uint32(159753));

PARAM_DEFINE_FINISH()