

% 重力加速度
CONST_DEFINE('CONSTANTS_ONE_G', 9.80665);						% m/s^2

% 标准大气压
CONSTANTS_STD_PRESSURE_PA_ = 101325.0;
CONST_DEFINE_FLOAT('CONSTANTS_STD_PRESSURE_PA', 101325.0);					% pascals (Pa)
CONST_DEFINE_FLOAT('CONSTANTS_STD_PRESSURE_KPA', CONSTANTS_STD_PRESSURE_PA_ / 1000.0);	% kilopascals (kPa)
CONST_DEFINE_FLOAT('CONSTANTS_STD_PRESSURE_MBAR', CONSTANTS_STD_PRESSURE_PA_ / 100.0);	% Millibar (mbar) (1 mbar', 100 Pa)
CONST_DEFINE_FLOAT('CONSTANTS_AIR_DENSITY_SEA_LEVEL_15C', 1.225);				% kg/m^3
CONST_DEFINE_FLOAT('CONSTANTS_AIR_GAS_CONST', 287.1);					% J/(kg * K)
CONST_DEFINE_FLOAT('CONSTANTS_ABSOLUTE_NULL_CELSIUS', -273.15);				% °C

% 地球半径
CONSTANTS_RADIUS_OF_EARTH_ = 6371000;
CONST_DEFINE_DOUBLE('CONSTANTS_RADIUS_OF_EARTH', 6371000);					% meters (m)
CONST_DEFINE_DOUBLE('CONSTANTS_RADIUS_OF_EARTH_F', CONSTANTS_RADIUS_OF_EARTH_);		% meters (m)
CONST_DEFINE_DOUBLE('CONSTANTS_EARTH_SPIN_RATE', 7.2921150e-5);

% 其它常量
CONST_DEFINE('MISSION_ORIGIN_MAVLINK', uint8(0));
CONST_DEFINE('MISSION_ORIGIN_ONBOARD', uint8(1));

clear CONSTANTS_RADIUS_OF_EARTH_ CONSTANTS_STD_PRESSURE_PA_
